### PR TITLE
Adding new file

### PR DESCRIPTION
**Pull request by freesoft**
It looks like the chapter is not just outdated but also original English version has A LOT changed than what current KR version was based on to translate. It's not simple change that sections are moved around. but I feel like this entire section is rewritten with more detailed images and explanation. I don't have time to translate it to KR right now but at least we need placeholder for the change.

Also please consider renaming the existing "deep-learning-intro.md" or remove it. The file doesn't exist anymore.

### CODE REVIEW

**Comment by muhyun** [comment]
First of all, thank you for pointing out the important stuff. Actually, we (including the original author) decided to be based on English version 0.5.0, and continuously update the content as English version is being revised. Considering your point, we are discussing to push the latest version of Chapter 1,2,3 and 4 to reflect any major change as soon as possible.

**Comment by mli** [comment]
Job d2l-ko/PR-7/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-ko/PR-7/

**Comment by mli** [comment]
Job d2l-ko/PR-7/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-ko/PR-7/

**Comment by astonzhang** [comment]
Thanks. We added the most updated machine translation corresponding to v0.17.1

**Pull request closed without merging**
